# johnvideo — macOS .app bundle build
#
# Pure-C engine + Objective-C++ AppKit UI shell, linked against Homebrew FFmpeg.
#   make        build the .app bundle
#   make run    build and launch
#   make clean  remove build output

APP_NAME  := johnvideo
BUILD_DIR := build
APP_DIR   := $(BUILD_DIR)/$(APP_NAME).app
MACOS_DIR := $(APP_DIR)/Contents/MacOS
BIN       := $(MACOS_DIR)/$(APP_NAME)

# FFmpeg from Homebrew (Apple Silicon keg-only path).
FFMPEG_PREFIX := $(shell brew --prefix ffmpeg)
export PKG_CONFIG_PATH := $(FFMPEG_PREFIX)/lib/pkgconfig:$(PKG_CONFIG_PATH)
FFMPEG_LIBS := libavformat libavcodec libavutil libswscale libswresample
FFMPEG_CFLAGS := $(shell pkg-config --cflags $(FFMPEG_LIBS))
FFMPEG_LDFLAGS := $(shell pkg-config --libs $(FFMPEG_LIBS))

CC        := clang
OBJCXX    := clang++

INCLUDES  := -Isrc/engine -Isrc/ui
WARN      := -Wall -Wextra
# -MMD -MP emit .d header-dependency files so editing a header rebuilds every
# object that includes it (otherwise stale objects get mismatched struct layouts).
DEPFLAGS  := -MMD -MP
CFLAGS    := $(WARN) -O2 -g $(DEPFLAGS) $(INCLUDES) $(FFMPEG_CFLAGS)
OBJCXXFLAGS := $(WARN) -O2 -g -std=c++17 -fobjc-arc $(DEPFLAGS) $(INCLUDES) $(FFMPEG_CFLAGS)
LDFLAGS   := $(FFMPEG_LDFLAGS) \
             -framework Cocoa -framework AVFoundation -framework CoreMedia \
             -framework CoreText -framework CoreGraphics -framework ImageIO \
             -framework UniformTypeIdentifiers

C_SRCS    := src/engine/timeline.c src/engine/decoder.c src/engine/export.c
MM_SRCS   := src/ui/main.mm src/ui/AppDelegate.mm src/ui/PreviewView.mm \
             src/ui/TimelineView.mm src/ui/Media.mm src/ui/AudioController.mm \
             src/ui/Project.mm

C_OBJS    := $(patsubst src/%.c,$(BUILD_DIR)/obj/%.o,$(C_SRCS))
MM_OBJS   := $(patsubst src/%.mm,$(BUILD_DIR)/obj/%.o,$(MM_SRCS))
OBJS      := $(C_OBJS) $(MM_OBJS)

ICON_SRC  := icon.png
ICNS      := $(BUILD_DIR)/AppIcon.icns
ICON_SIZES := 16 32 128 256 512

.PHONY: all run run-direct clean install test test-ui test-export test-project
all: $(APP_DIR)

# ---- Tests ---------------------------------------------------------------
# `make test` runs every suite; the test-* targets run one each. Each test file
# owns its own main(), so we link all app objects EXCEPT main.o.
NONMAIN_OBJS := $(filter-out $(BUILD_DIR)/obj/ui/main.o,$(OBJS))

test: test-export test-project test-ui
	@echo "all test suites passed"

# Headless UI behaviour suite: synthesizes NSEvents into real views.
test-ui: $(OBJS)
	$(OBJCXX) $(OBJCXXFLAGS) test/test_ui.mm $(NONMAIN_OBJS) $(LDFLAGS) -o $(BUILD_DIR)/test_ui
	$(BUILD_DIR)/test_ui

# Engine -> MP4 (compositor + mixer + encode/mux). Pure C + FFmpeg.
test-export: $(C_OBJS)
	$(CC) $(CFLAGS) test/test_export.c $(C_OBJS) $(FFMPEG_LDFLAGS) -o $(BUILD_DIR)/test_export
	$(BUILD_DIR)/test_export

# .jvp save/load round-trip (Project.mm + Media.mm + engine).
test-project: $(OBJS)
	$(OBJCXX) $(OBJCXXFLAGS) test/test_project.mm $(NONMAIN_OBJS) $(LDFLAGS) -o $(BUILD_DIR)/test_project
	$(BUILD_DIR)/test_project

# App icon: build a multi-size .icns from icon.png (only when it changes).
$(ICNS): $(ICON_SRC)
	@rm -rf $(BUILD_DIR)/AppIcon.iconset && mkdir -p $(BUILD_DIR)/AppIcon.iconset
	@for s in $(ICON_SIZES); do \
		sips -z $$s $$s $(ICON_SRC) --out $(BUILD_DIR)/AppIcon.iconset/icon_$${s}x$${s}.png >/dev/null; \
		d=$$((s*2)); sips -z $$d $$d $(ICON_SRC) --out $(BUILD_DIR)/AppIcon.iconset/icon_$${s}x$${s}@2x.png >/dev/null; \
	done
	@iconutil -c icns $(BUILD_DIR)/AppIcon.iconset -o $@

$(APP_DIR): $(BIN) Info.plist $(ICNS)
	@mkdir -p $(APP_DIR)/Contents/Resources
	@cp Info.plist $(APP_DIR)/Contents/Info.plist
	@cp $(ICNS) $(APP_DIR)/Contents/Resources/AppIcon.icns
	@echo "APPL????" > $(APP_DIR)/Contents/PkgInfo
	@echo "Built $(APP_DIR)"

$(BIN): $(OBJS)
	@mkdir -p $(MACOS_DIR)
	$(OBJCXX) $(OBJS) $(LDFLAGS) -o $@

$(BUILD_DIR)/obj/%.o: src/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/obj/%.o: src/%.mm
	@mkdir -p $(dir $@)
	$(OBJCXX) $(OBJCXXFLAGS) -c $< -o $@

# Header dependencies (generated by -MMD); safe if absent.
-include $(OBJS:.o=.d)

# Launch as a bundle (via open) so macOS associates Info.plist and can grant
# microphone access. Use `make run-direct` to run the raw binary for stderr logs.
run: all
	open $(APP_DIR)

run-direct: all
	$(BIN)

# Install into /Applications (override with `make install INSTALL_DIR=~/Applications`).
INSTALL_DIR ?= /Applications
install: all
	@mkdir -p "$(INSTALL_DIR)"
	rm -rf "$(INSTALL_DIR)/John Video.app"
	cp -R $(APP_DIR) "$(INSTALL_DIR)/John Video.app"
	@/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$(INSTALL_DIR)/John Video.app" 2>/dev/null || true
	@echo "Installed to $(INSTALL_DIR)/John Video.app"

clean:
	rm -rf $(BUILD_DIR)
